apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: german-credit
spec:
  default:
    predictor:
      custom:
        container:
          image: rzgry/german-credit
    explainer:
      custom:
        container:
          name: explainer
          image: rzgry/aifserver
          command:
            [
              "python",
              "-m",
              "aifserver",
              "--predictor_host",
              "german-credit-predictor-default.default.svc.cluster.local",
              "--model_name",
              "german-credit",
              "--feature_names",
              "age",
              "sex",
              "credit_history=Delay",
              "credit_history=None/Paid",
              "credit_history=Other",
              "savings=500+",
              "savings=<500",
              "savings=Unknown/None",
              "employment=1-4 years",
              "employment=4+ years",
              "employment=unemployed",
              "--label_names",
              "credit",
              "--favorable_label",
              "1",
              "--unfavorable_label",
              "2",
              "--privileged_groups",
              '{"age": 1}',
              "--unprivileged_groups",
              '{"age": 0}',
            ]
          imagePullPolicy: Always
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "2"
